name: 'OctoFirst analysis'
description: 'Runs OctoFirst analysis on your project'
author: 'OctoFirst'
branding:
  icon: bar-chart
  color: blue
runs:
  using: 'composite'

  steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v1

    - name: Analyse
      run: |
        #!/bin/sh -l
        set -e

        # this file is (and will forever be) open source. Feel free to check it out
        url=https://raw.githubusercontent.com/OctoFirst/octofirst-action/main/analyze.sh
        curl -sSL $url | bash -s  

        echo Finished
      shell: bash
      env:
        OCTOFIRST_SECRET: ${{ inputs.octofirst_secret }}


inputs:
  octofirst_secret:
    description: 'Your secret token for OctoFirst application'
    required: true