name: 'OctoFirst analysis'
description: 'Runs OctoFirst analysis on your project'
author: 'OctoFirst'
branding:
  icon: bar-chart
  color: blue
runs:
  using: 'composite'

  steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: sources

    - name: Checkout OctoFirst Action
      uses: actions/checkout@v4
      with:
        repository: OctoFirst/octofirst-action
        path: octofirst-action
        ref: ${{ inputs.octofirst_action_ref }}
        token: '${{ github.token }}'

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install Lizard
      run: |
        python -m pip install --upgrade pip
        pip install lizard
      shell: bash

    - name: Install PhpMetrics
      run: |
        curl -L https://github.com/phpmetrics/PhpMetrics/raw/refs/heads/master/releases/phpmetrics-linux-x86_64 \
            -o /usr/local/bin/phpmetrics
        chmod +x /usr/local/bin/phpmetrics
      shell: bash
      
    - name: Analyse
      run: |
        #!/bin/sh -l
        set -e
        ls -al
        
        # this file is (and will forever be) open source. Feel free to check it out
        bash ./octofirst-action/analyze.sh sources

        echo Finished
      shell: bash
      env:
        OCTOFIRST_SECRET: ${{ inputs.octofirst_secret }}

inputs:
  octofirst_secret:
    description: 'Your secret token for OctoFirst application'
    required: true
  octofirst_action_ref:
    description: 'The branch or tag to use for the OctoFirst Action'
    required: false
    default: ''